name: manage-azure-policy-9bd52bcd
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_SQL_Managed_Instance_should_have_Azure_Active_Directory_Only_Authentication_enabled_78215662-041e-49ed-a9dd-5385911b3a1f/**'
#      - .github/workflows/manage-azure-policy-9bd52bcd.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_9bd52bcd}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_SQL_Managed_Instance_should_have_Azure_Active_Directory_Only_Authentication_enabled_78215662-041e-49ed-a9dd-5385911b3a1f/**
